### PR TITLE
[WIP] doc improvement

### PR DESCRIPTION
**Pull request by mosn**
adds missing space. please do not merge as I will update this PR as I progress through docs.

### CODE REVIEW

**Comment by arcticicestudio** [comment]
Hi @mosn :wave:, thanks in advance for your contribution :+1:
Even though I use VS Code with spell checking extensions and the CI/CD pipelines using the [remark-lint Markdown style guide rule set][md-stylg] there are still some small typos and grammar issues. Haven't got the time and focus to fix them so I really appreciate every help :smile: 

[md-stylg]: https://github.com/arcticicestudio/remark-preset-lint-arcticicestudio

**Comment by mosn** [comment]
Hey @arcticicestudio That's the only thing I can do face the empire of perfection. 
As mentioned I am going through all the docs to familiarize myself with the setup and will update this PR as I progress. 🙏

**Comment by arcticicestudio** [comment]
@mosn Is this still WIP or ready to be merged?

**Comment by mosn** [comment]
@arcticicestudio as of #160 I am up to date and LGTM. So we can close it.

**Pull request merged**
